num1 = int(input("Digite o primeiro número inteiro: "))
num2 = int(input("Digite o segundo número inteiro: "))
peso1 = 3
peso2 = 4
medpod = (num1 * peso1 + num2 * peso2) / (peso1 + peso2)
print("   ")
print(f"Os números digitados foram {num1} e {num2}.")
print("   ")
print(f"A soma dos dois números inteiros digitados é: {num1 + num2}")
print("   ")
print(f"A média simples dos dois números inteiros é: {(num1 + num2) / 2}")
print("   ")
print(f"A média ponderada dos dois números inteiros, com os pesos 3 e 4 é: {medpod}")
print("   ")
peso3 = int(input("Digite o primeiro peso: "))
peso4 = int(input("Digite o segundo peso: "))
medpod2 = (num1 * peso3 + num2 * peso4) / (peso3 + peso4)
print("   ")
print(f"A média ponderada dos dois números escolhidos, com os pesos {peso3} e {peso4} é: {medpod2}")
